### PR TITLE
re-generate the peripheral::* modules one more time

### PR DESCRIPTION
**Pull request by japaric**
to pickup the latest changes in svd2rust

### CODE REVIEW

**Comment by japaric** [comment]
@homunkulus r+

**Comment by homunkulus** [comment]
:pushpin: Commit 02ef29d has been approved by `japaric`

**Comment by homunkulus** [comment]
:hourglass: Testing commit 02ef29d with merge 02ef29d...

**Comment by homunkulus** [comment]
:sunny: Test successful - [status-travis](https://travis-ci.org/japaric/f3/builds/166258285)
Approved by: japaric
Pushing 02ef29db8165a8d159e3635e5570e222c71242c3 to master...

**Pull request merged**
