### PR TITLE
re-export cortex-m's bkpt! macro

### PR DESCRIPTION
**Pull request by japaric**

### CODE REVIEW

**Comment by japaric** [comment]
@homunkulus r+

**Comment by homunkulus** [comment]
:pushpin: Commit 0792778 has been approved by `japaric`

**Comment by homunkulus** [comment]
:hourglass: Testing commit 0792778 with merge 0792778...

**Comment by homunkulus** [comment]
:broken_heart: Test failed - [status-travis](https://travis-ci.org/japaric/f3/builds/168680385)

**Comment by japaric** [comment]
@homunkulus r+

**Comment by homunkulus** [comment]
:pushpin: Commit ab1f0e6 has been approved by `japaric`

**Comment by homunkulus** [comment]
:hourglass: Testing commit ab1f0e6 with merge ab1f0e6...

**Comment by homunkulus** [comment]
:sunny: Test successful - [status-travis](https://travis-ci.org/japaric/f3/builds/168683370)
Approved by: japaric
Pushing ab1f0e6bd3439edf9459416d83486e9d0aa76200 to master...

**Pull request merged**
