### PR TITLE
tweak ABIs

### PR DESCRIPTION
**Pull request by japaric**

### CODE REVIEW

**Comment by japaric** [comment]
@homunkulus r+

**Comment by homunkulus** [comment]
:pushpin: Commit 10694b4 has been approved by `japaric`

**Comment by homunkulus** [comment]
:hourglass: Testing commit 10694b4 with merge 10694b4...

**Comment by homunkulus** [comment]
:sunny: Test successful - [status-travis](https://travis-ci.org/japaric/f3/builds/175123551)
Approved by: japaric
Pushing 10694b4ad6badaf9a6048925fc7ef866fe74e8bf to master...

**Pull request merged**
