### PR TITLE
drop target files

### PR DESCRIPTION
**Pull request by japaric**

### CODE REVIEW

**Comment by japaric** [comment]
@homunkulus r+

**Comment by homunkulus** [comment]
:pushpin: Commit 99bb011 has been approved by `japaric`

**Comment by homunkulus** [comment]
:hourglass: Testing commit 99bb011 with merge b58f90f...

**Comment by homunkulus** [comment]
:sunny: Test successful - [status-travis](https://travis-ci.org/japaric/f3/builds/165708873)
Approved by: japaric
Pushing b58f90f57ceb7fb66b58350a3eb246cb2fc6db5a to master...

**Pull request merged**
