### PR TITLE
low level access to SPI

### PR DESCRIPTION
**Pull request by japaric**

### CODE REVIEW

**Comment by japaric** [comment]
@homunkulus r+

**Comment by homunkulus** [comment]
:pushpin: Commit a409420 has been approved by `japaric`

**Comment by homunkulus** [comment]
:hourglass: Testing commit a409420 with merge a409420...

**Comment by homunkulus** [comment]
:broken_heart: Test failed - [status-travis](https://travis-ci.org/japaric/f3/builds/166325231)

**Comment by japaric** [comment]
@homunkulus r+

**Comment by homunkulus** [comment]
:pushpin: Commit 9d94e83 has been approved by `japaric`

**Comment by homunkulus** [comment]
:hourglass: Testing commit 9d94e83 with merge 9d94e83...

**Comment by homunkulus** [comment]
:sunny: Test successful - [status-travis](https://travis-ci.org/japaric/f3/builds/166325951)
Approved by: japaric
Pushing 9d94e8353110ffb8436f256e0e0be6e76ce2a20c to master...

**Pull request merged**
