### PR TITLE
remove duplicate example about overriding an exception

### PR DESCRIPTION
**Pull request by japaric**

### CODE REVIEW

**Comment by japaric** [comment]
@homunkulus r+

**Comment by homunkulus** [comment]
:pushpin: Commit a7fa00c has been approved by `japaric`

**Comment by homunkulus** [comment]
:hourglass: Testing commit a7fa00c with merge a7fa00c...

**Comment by homunkulus** [comment]
:sunny: Test successful - [status-travis](https://travis-ci.org/japaric/f3/builds/165992088)
Approved by: japaric
Pushing a7fa00cdc07d06b46dfccc6478e2a28defe9faa0 to master...

**Pull request merged**
