### PR TITLE
re-generate peripheral::* modules

### PR DESCRIPTION
**Pull request by japaric**

### CODE REVIEW

**Comment by japaric** [comment]
@homunkulus r+

**Comment by homunkulus** [comment]
:pushpin: Commit ed7f8c4 has been approved by `japaric`

**Comment by homunkulus** [comment]
:hourglass: Testing commit ed7f8c4 with merge ed7f8c4...

**Comment by homunkulus** [comment]
:sunny: Test successful - [status-travis](https://travis-ci.org/japaric/f3/builds/166326396)
Approved by: japaric
Pushing ed7f8c497773e6076c85d629b5ca1c92764bc2e4 to master...

**Pull request merged**
