### PR TITLE
regenerate peripheral::* modules

### PR DESCRIPTION
**Pull request by japaric**
to include improvements in doc generation

### CODE REVIEW

**Comment by japaric** [comment]
@homunkulus r+

**Comment by homunkulus** [comment]
:pushpin: Commit 7e8539e has been approved by `japaric`

**Comment by homunkulus** [comment]
:hourglass: Testing commit 7e8539e with merge 7e8539e...

**Comment by homunkulus** [comment]
:sunny: Test successful - [status-travis](https://travis-ci.org/japaric/f3/builds/166219862)
Approved by: japaric
Pushing 7e8539ecec69621d480e569868b3dcd3e498982a to master...

**Pull request merged**
