### PR TITLE
bump compiler-builtins-snapshot, format floats in fpu example

### PR DESCRIPTION
**Pull request by japaric**

### CODE REVIEW

**Comment by japaric** [comment]
@homunkulus r+

**Comment by homunkulus** [comment]
:pushpin: Commit f2ec6ab has been approved by `japaric`

**Comment by homunkulus** [comment]
:hourglass: Testing commit f2ec6ab with merge f2ec6ab...

**Comment by homunkulus** [comment]
:broken_heart: Test failed - [status-travis](https://travis-ci.org/japaric/f3/builds/166062176)

**Comment by japaric** [comment]
@homunkulus r+

**Comment by homunkulus** [comment]
:pushpin: Commit a12403b has been approved by `japaric`

**Comment by homunkulus** [comment]
:hourglass: Testing commit a12403b with merge a12403b...

**Comment by japaric** [comment]
@homunkulus r-

**Comment by japaric** [comment]
@homunkulus r+

**Comment by homunkulus** [comment]
:pushpin: Commit d88b741 has been approved by `japaric`

**Comment by homunkulus** [comment]
:hourglass: Testing commit d88b741 with merge d88b741...

**Comment by homunkulus** [comment]
:sunny: Test successful - [status-travis](https://travis-ci.org/japaric/f3/builds/166063527)
Approved by: japaric
Pushing d88b741b757ad090fd7769a80d11e5c6c78b57d6 to master...

**Pull request merged**
