### PR TITLE
refactor examples for RTFM v2

### PR DESCRIPTION
**Pull request by getreu**
this builds on @brandonedens work.

### CODE REVIEW

**Comment by japaric** [comment]
I'm not going to be able to test this on hardware any time soon but I'll trust you folks :-)

@homunkulus r+

**Comment by homunkulus** [comment]
:pushpin: Commit e5042ef has been approved by `japaric`

**Comment by homunkulus** [comment]
:hourglass: Testing commit e5042ef with merge e5042ef...

**Comment by homunkulus** [comment]
:broken_heart: Test failed - [status-travis](https://travis-ci.org/japaric/f3/builds/278103042?utm_source=github_status&utm_medium=notification)

**Comment by japaric** [comment]
@homunkulus r+

**Comment by homunkulus** [comment]
:pushpin: Commit 29526c2 has been approved by `japaric`

**Comment by homunkulus** [comment]
:hourglass: Testing commit 29526c2 with merge 29526c2...

**Comment by homunkulus** [comment]
:sunny: Test successful - [status-travis](https://travis-ci.org/japaric/f3/builds/278108843?utm_source=github_status&utm_medium=notification)
Approved by: japaric
Pushing 29526c2b99c2a50bdf96a249e55b5fc316404af9 to master...

**Pull request merged**
