### PR TITLE
tweak CI

### PR DESCRIPTION
**Pull request by japaric**

### CODE REVIEW

**Comment by japaric** [comment]
@homunkulus r+

**Comment by homunkulus** [comment]
:pushpin: Commit a82a654 has been approved by `japaric`

**Comment by homunkulus** [comment]
:hourglass: Testing commit a82a654 with merge a82a654...

**Comment by homunkulus** [comment]
:sunny: Test successful - [status-travis](https://travis-ci.org/japaric/f3/builds/185783270)
Approved by: japaric
Pushing a82a654322a4aeac51cac8b2bea9fb99ee5b0b4a to master...

**Pull request merged**
