### PR TITLE
make all the APIs async, drop all the startup stuff

### PR DESCRIPTION
**Pull request by japaric**
to use this crate you must now use the cortex-m-quickstart template. See the
crate level documentation for instructions.

### CODE REVIEW

**Comment by japaric** [comment]
@homunkulus r+

**Comment by homunkulus** [comment]
:pushpin: Commit ad11006 has been approved by `japaric`

**Comment by homunkulus** [comment]
:hourglass: Testing commit ad11006 with merge ad11006...

**Comment by japaric** [comment]
@homunkulus r+

**Comment by homunkulus** [comment]
:pushpin: Commit beb823f has been approved by `japaric`

**Comment by homunkulus** [comment]
:hourglass: Testing commit beb823f with merge beb823f...

**Comment by japaric** [comment]
@homunkulus r+

**Comment by homunkulus** [comment]
:pushpin: Commit e2fecfb has been approved by `japaric`

**Comment by homunkulus** [comment]
:hourglass: Testing commit e2fecfb with merge e2fecfb...

**Comment by homunkulus** [comment]
:sunny: Test successful - [status-travis](https://travis-ci.org/japaric/f3/builds/227037651?utm_source=github_status&utm_medium=notification)
Approved by: japaric
Pushing e2fecfbdd060870272cdca2c5b858f7289d707f5 to master...

**Pull request merged**
