### PR TITLE
add a script to (re)generate the peripheral::* modules

### PR DESCRIPTION
**Pull request by japaric**
and regenerate them while we are at it

### CODE REVIEW

**Comment by japaric** [comment]
@homunkulus r+

**Comment by homunkulus** [comment]
:pushpin: Commit d905136 has been approved by `japaric`

**Comment by homunkulus** [comment]
:hourglass: Testing commit d905136 with merge d905136...

**Comment by homunkulus** [comment]
:sunny: Test successful - [status-travis](https://travis-ci.org/japaric/f3/builds/167516551)
Approved by: japaric
Pushing d90513659afa5c88db684e0eb262201354183fe7 to master...

**Pull request merged**
