### PR TITLE
timeit module

### PR DESCRIPTION
**Pull request by japaric**

### CODE REVIEW

**Comment by japaric** [comment]
@homunkulus r+

**Comment by homunkulus** [comment]
:pushpin: Commit 9557e38 has been approved by `japaric`

**Comment by homunkulus** [comment]
:hourglass: Testing commit 9557e38 with merge 9557e38...

**Comment by homunkulus** [comment]
:broken_heart: Test failed - [status-travis](https://travis-ci.org/japaric/f3/builds/169145255)

**Comment by japaric** [comment]
@homunkulus r+

**Comment by homunkulus** [comment]
:pushpin: Commit a3f6d52 has been approved by `japaric`

**Comment by homunkulus** [comment]
:hourglass: Testing commit a3f6d52 with merge a3f6d52...

**Comment by japaric** [comment]
@homunkulus r+

**Comment by homunkulus** [comment]
:pushpin: Commit 5314c6b has been approved by `japaric`

**Comment by homunkulus** [comment]
:hourglass: Testing commit 5314c6b with merge 5314c6b...

**Comment by homunkulus** [comment]
:sunny: Test successful - [status-travis](https://travis-ci.org/japaric/f3/builds/169148080)
Approved by: japaric
Pushing 5314c6bc5a17b6247cc45c12b1dfeae9ac5bac90 to master...

**Pull request merged**
