### PR TITLE
use svd2rust to generate the peripheral::* modules

### PR DESCRIPTION
**Pull request by japaric**

### CODE REVIEW

**Comment by japaric** [comment]
@homunkulus r+

**Comment by homunkulus** [comment]
:pushpin: Commit d3aea24 has been approved by `japaric`

**Comment by homunkulus** [comment]
:hourglass: Testing commit d3aea24 with merge d3aea24...

**Comment by japaric** [comment]
@homunkulus r+

**Comment by homunkulus** [comment]
:pushpin: Commit 5c9053a has been approved by `japaric`

**Comment by homunkulus** [comment]
:hourglass: Testing commit 5c9053a with merge 5c9053a...

**Comment by homunkulus** [comment]
:sunny: Test successful - [status-travis](https://travis-ci.org/japaric/f3/builds/166143985)
Approved by: japaric
Pushing 5c9053ae3114f0cb2ee5fb02548057da6607eb21 to master...

**Pull request merged**
