### PR TITLE
high level API over the LSM303DLHC + LED compass example

### PR DESCRIPTION
**Pull request by japaric**

### CODE REVIEW

**Comment by japaric** [comment]
@homunkulus r+

**Comment by homunkulus** [comment]
:pushpin: Commit 9aa5ae8 has been approved by `japaric`

**Comment by homunkulus** [comment]
:hourglass: Testing commit 9aa5ae8 with merge 9aa5ae8...

**Comment by homunkulus** [comment]
:sunny: Test successful - [status-travis](https://travis-ci.org/japaric/f3/builds/166361090)
Approved by: japaric
Pushing 9aa5ae8135aa5f40ce15e761e72075902ac504f4 to master...

**Pull request merged**
