### PR TITLE
change example/minimal to generate a binary with minimal size

### PR DESCRIPTION
**Pull request by japaric**

### CODE REVIEW

**Comment by japaric** [comment]
@homunkulus r+

**Comment by homunkulus** [comment]
:pushpin: Commit 2d28ca4 has been approved by `japaric`

**Comment by homunkulus** [comment]
:hourglass: Testing commit 2d28ca4 with merge 2d28ca4...

**Comment by japaric** [comment]
@homunkulus r+

**Comment by homunkulus** [comment]
:pushpin: Commit 525e610 has been approved by `japaric`

**Comment by homunkulus** [comment]
:hourglass: Testing commit 525e610 with merge 525e610...

**Comment by homunkulus** [comment]
:broken_heart: Test failed - [status-travis](https://travis-ci.org/japaric/f3/builds/173434528)

**Comment by japaric** [comment]
@homunkulus r+

**Comment by homunkulus** [comment]
:pushpin: Commit 2d28ca4 has been approved by `japaric`

**Comment by homunkulus** [comment]
:hourglass: Testing commit 2d28ca4 with merge 2d28ca4...

**Comment by homunkulus** [comment]
:sunny: Test successful - [status-travis](https://travis-ci.org/japaric/f3/builds/173436503)
Approved by: japaric
Pushing 2d28ca4e59f5971113d07992968bc9230357d08c to master...

**Pull request merged**
