### PR TITLE
disable ThinLTO

### PR DESCRIPTION
**Pull request by japaric**

### CODE REVIEW

**Comment by japaric** [comment]
@homunkulus r+

**Comment by homunkulus** [comment]
:pushpin: Commit 1ff6d3a has been approved by `japaric`

**Comment by homunkulus** [comment]
:hourglass: Testing commit 1ff6d3ae67d239296e8911449ce1eb3d29952f0a with merge d7ec012c3be3da9fdd205b9f1e703e708ba37297...

**Comment by homunkulus** [comment]
:sunny: Test successful - [status-travis](https://travis-ci.org/japaric/f3/builds/333660154?utm_source=github_status&utm_medium=notification)
Approved by: japaric
Pushing d7ec012c3be3da9fdd205b9f1e703e708ba37297 to master...

**Pull request merged**
