### PR TITLE
add "rt" Cargo feature

### PR DESCRIPTION
**Pull request by japaric**

### CODE REVIEW

**Comment by japaric** [comment]
@homunkulus r+

**Comment by homunkulus** [comment]
:pushpin: Commit ccef77b has been approved by `japaric`

**Comment by homunkulus** [comment]
:hourglass: Testing commit ccef77b30a42bb5e36804373555a5d710ed50e5c with merge 2797ea171b221cd06630fe348246ef4d35d0cbb9...

**Comment by japaric** [comment]
@homunkulus r+

**Comment by homunkulus** [comment]
:pushpin: Commit e412cd0 has been approved by `japaric`

**Comment by homunkulus** [comment]
:hourglass: Testing commit e412cd06100f3b8a38d0ed29fea7599602c7aa64 with merge d912e9e0f91f1850f82481a7ec40ab5e0cc5c300...

**Comment by homunkulus** [comment]
:broken_heart: Test failed - [status-travis](https://travis-ci.org/japaric/f3/builds/331161538?utm_source=github_status&utm_medium=notification)

**Comment by japaric** [comment]
@homunkulus r+

**Comment by homunkulus** [comment]
:pushpin: Commit 1a9775c has been approved by `japaric`

**Comment by homunkulus** [comment]
:hourglass: Testing commit 1a9775caa8794c4dedc47eb3fc223e76fc382f9d with merge 0e120a2fb49133e09c17361ccf3fcf21e9e6f36a...

**Comment by homunkulus** [comment]
:sunny: Test successful - [status-travis](https://travis-ci.org/japaric/f3/builds/331163022?utm_source=github_status&utm_medium=notification)
Approved by: japaric
Pushing 0e120a2fb49133e09c17361ccf3fcf21e9e6f36a to master...

**Pull request merged**
