### PR TITLE
lsm303dlhc: measure acceleration in the [-8g, +8g] range

### PR DESCRIPTION
**Pull request by japaric**

### CODE REVIEW

**Comment by japaric** [comment]
@homunkulus r+

**Comment by homunkulus** [comment]
:pushpin: Commit 5970daf has been approved by `japaric`

**Comment by homunkulus** [comment]
:hourglass: Testing commit 5970daf with merge 5970daf...

**Comment by homunkulus** [comment]
:sunny: Test successful - [status-travis](https://travis-ci.org/japaric/f3/builds/169962238)
Approved by: japaric
Pushing 5970dafc73bd9ced889f12e0aa7a5da942406267 to master...

**Pull request merged**
