### PR TITLE
replace the timeit module with time::Instant

### PR DESCRIPTION
**Pull request by japaric**

### CODE REVIEW

**Comment by japaric** [comment]
@homunkulus r+

**Comment by homunkulus** [comment]
:pushpin: Commit 314d155 has been approved by `japaric`

**Comment by homunkulus** [comment]
:hourglass: Testing commit 314d155 with merge 314d155...

**Comment by homunkulus** [comment]
:sunny: Test successful - [status-travis](https://travis-ci.org/japaric/f3/builds/169944119)
Approved by: japaric
Pushing 314d1551efba77e6b0fc9f701c53b79b0935432f to master...

**Pull request merged**
