### PR TITLE
compiler-builtins must always be compiled with +memcpy

### PR DESCRIPTION
**Pull request by japaric**
remove it from the list of default features

### CODE REVIEW

**Comment by japaric** [comment]
@homunkulus r+

**Comment by homunkulus** [comment]
:pushpin: Commit e814e18 has been approved by `japaric`

**Comment by homunkulus** [comment]
:hourglass: Testing commit e814e18 with merge e814e18...

**Comment by homunkulus** [comment]
:sunny: Test successful - [status-travis](https://travis-ci.org/japaric/f3/builds/169319469)
Approved by: japaric
Pushing e814e18698f73b414d6de092059584afc5baac81 to master...

**Pull request merged**
