### PR TITLE
add the final version of the LED compass example

### PR DESCRIPTION
**Pull request by japaric**
this example uses a pure Rust implementation of atan2f

### CODE REVIEW

**Comment by japaric** [comment]
@homunkulus r+

**Comment by homunkulus** [comment]
:pushpin: Commit 7c9f2db has been approved by `japaric`

**Comment by homunkulus** [comment]
:hourglass: Testing commit 7c9f2db with merge 7c9f2db...

**Comment by homunkulus** [comment]
:sunny: Test successful - [status-travis](https://travis-ci.org/japaric/f3/builds/167920800)
Approved by: japaric
Pushing 7c9f2db31594f8d217db16022e0b5df7bd6dbc34 to master...

**Pull request merged**
