### PR TITLE
homu support

### PR DESCRIPTION
**Pull request by japaric**

### CODE REVIEW

**Comment by japaric** [comment]
@homunkulus r+

**Comment by homunkulus** [comment]
:pushpin: Commit bb0828b has been approved by `japaric`

**Comment by homunkulus** [comment]
:hourglass: Testing commit bb0828b with merge bb0828b...

**Comment by homunkulus** [comment]
:sunny: Test successful - [status-travis](https://travis-ci.org/japaric/f3/builds/165400952)
Approved by: japaric
Pushing bb0828b56f1e1619bc81842bd5e4529acd10b1ac to master...

**Pull request merged**
