### PR TITLE
remove webhook

### PR DESCRIPTION
**Pull request by japaric**

### CODE REVIEW

**Comment by japaric** [comment]
@homunkulus r+

**Comment by homunkulus** [comment]
:pushpin: Commit a33de29 has been approved by `japaric`

**Comment by homunkulus** [comment]
:hourglass: Testing commit a33de29 with merge a33de29...

**Comment by homunkulus** [comment]
:sunny: Test successful - [status-travis](https://travis-ci.org/japaric/f3/builds/174052124)
Approved by: japaric
Pushing a33de2905c0336ecf3a68cef8f84333bb1d30fc3 to master...

**Pull request merged**
