### PR TITLE
delay::ms: switch back to busy waiting

### PR DESCRIPTION
**Pull request by japaric**
the interrupt based approach has problems when compiled in release mode

### CODE REVIEW

**Comment by japaric** [comment]
@homunkulus r+

**Comment by homunkulus** [comment]
:pushpin: Commit d4bf297 has been approved by `japaric`

**Comment by homunkulus** [comment]
:hourglass: Testing commit d4bf297 with merge d4bf297...

**Comment by homunkulus** [comment]
:sunny: Test successful - [status-travis](https://travis-ci.org/japaric/f3/builds/167214833)
Approved by: japaric
Pushing d4bf297ef8b5dbafd06ccff721e9e6d3ceee6e49 to master...

**Pull request merged**
