### PR TITLE
replace the peripheral module with the stm32f30x-memory-map crate

### LINKED ISSUE #53: split memory map into its own crate
That should improve recompilation times of this crate (both as a lib and its examples).

And if we get some easy way to build dependencies in release mode while the top crate is still compiled in debug mode, that should improve a lot run time of examples compiled in debug mode.

### PR DESCRIPTION
**Pull request by japaric**
closes #53

### CODE REVIEW

**Comment by japaric** [comment]
@homunkulus try

**Comment by homunkulus** [comment]
:hourglass: Trying commit 214e952 with merge 214e952...

**Comment by homunkulus** [comment]
:sunny: Test successful - [status-travis](https://travis-ci.org/japaric/f3/builds/175772503)
State: approved= try=True

**Comment by japaric** [comment]
@homunkulus r+

**Comment by homunkulus** [comment]
:pushpin: Commit d8fb1a0 has been approved by `japaric`

**Comment by homunkulus** [comment]
:hourglass: Testing commit d8fb1a0 with merge d8fb1a0...

**Comment by homunkulus** [comment]
:sunny: Test successful - [status-travis](https://travis-ci.org/japaric/f3/builds/175783438)
Approved by: japaric
Pushing d8fb1a048e999059ca09c88c9bc6a606f2cce802 to master...

**Pull request merged**
