### PR TITLE
bump dependencies' versions

### PR DESCRIPTION
**Pull request by japaric**

### CODE REVIEW

**Comment by japaric** [comment]
cc @susurrus

**Comment by Susurrus** [comment]
This compiles for me with the exception of missing the `panic_fmt` lang item when building with `xargo`. If I just run `xargo build --example hello` after cloning this branch I get a "can't find crate for std" error. If I follow the quickstart docs and delete `build.rs` and `memory.x` I get the same error. So I'm not sure what I'm doing wrong, but I can't fully test this right now.

**Comment by japaric** [comment]
@Susurrus You need to [specify the `--target`](https://docs.rs/cortex-m-quickstart/0.2.1/cortex_m_quickstart/#forgot-to-set-a-default-build-target) otherwise you are building for the host.

**Comment by Susurrus** [comment]
@japaric Thanks, that was it. I had thought that was already specified in `.cargo/config`, but it looks like it's not. Since this is a board-specific crate, maybe the `[build]` target should be specified there as well?

**Comment by japaric** [comment]
> Since this is a board-specific crate, maybe the [build] target should be specified there as well?

Unfortunately if we do that then we can't publish this crate because `cargo publish` / `cargo package` would fail.

**Comment by Susurrus** [comment]
Yeah, I figured there was a reason it couldn't be done.

Anyways, this appears to work here. This branch doesn't seem to work in my small example project with RTFM, however, which what made me post about this in the first place. I was trying to follow your blog post for the 0.2 release and use the `f3` crate and its `stm32f30x` device crate instead of the `stm32f103xx` crate so I could work with my F3DISCOVERY board. but I seem to be missing something. I still get a missing `panic_fmt` error. My dependencies are `cortex-m-rtfm`, `cortex-m-semihosting`, and `f3`, but I didn't specify any features but that shouldn't be necessary by my understanding.

**Comment by japaric** [comment]
@Susurrus Did you start from quickstart v2? It enables the "abort-on-panic" feature of the cortex-m-rt crate and that provides the panic_fmt lang item.

If you already have that then maybe have CARGO_INCREMENTAL enabled? That doesn't work well with no-std applications, IME, and can produce bizarre errors. If you have that enabled then disable it and call `cargo clean` because you may be using some stale cache.

**Comment by Susurrus** [comment]
I'm having linking problems now, but they seem more a factor , but I think I'm past the whole Rust compilation process and it's just cross-compilation issues on my end. So I think this is fine to merge.

**Comment by japaric** [comment]
@homunkulus r+

**Comment by homunkulus** [comment]
:pushpin: Commit 1d27248 has been approved by `japaric`

**Comment by homunkulus** [comment]
:hourglass: Testing commit 1d27248 with merge 1d27248...

**Comment by homunkulus** [comment]
:broken_heart: Test failed - [status-travis](https://travis-ci.org/japaric/f3/builds/260047004?utm_source=github_status&utm_medium=notification)

**Comment by japaric** [comment]
@homunkulus r+

**Comment by homunkulus** [comment]
:pushpin: Commit ffbfe25 has been approved by `japaric`

**Comment by homunkulus** [comment]
:hourglass: Testing commit ffbfe25 with merge ffbfe25...

**Comment by homunkulus** [comment]
:sunny: Test successful - [status-travis](https://travis-ci.org/japaric/f3/builds/260048173?utm_source=github_status&utm_medium=notification)
Approved by: japaric
Pushing ffbfe25b0f8ac80ed0b794656968d23af500205b to master...

**Pull request merged**
