### PR TITLE
don't call zero_bss or init_data if .bss or .data is empty

### PR DESCRIPTION
**Pull request by japaric**

### CODE REVIEW

**Comment by japaric** [comment]
@homunkulus r+

**Comment by homunkulus** [comment]
:pushpin: Commit 0cf0cf6 has been approved by `japaric`

**Comment by homunkulus** [comment]
:hourglass: Testing commit 0cf0cf6 with merge 0cf0cf6...

**Comment by homunkulus** [comment]
:sunny: Test successful - [status-travis](https://travis-ci.org/japaric/f3/builds/169806486)
Approved by: japaric
Pushing 0cf0cf642d95d28dc4561c570c0f2c8f39b3915a to master...

**Pull request merged**
