### PR TITLE
serial port support

### PR DESCRIPTION
**Pull request by japaric**

### CODE REVIEW

**Comment by japaric** [comment]
@homunkulus r+

**Comment by homunkulus** [comment]
:pushpin: Commit d392fba has been approved by `japaric`

**Comment by homunkulus** [comment]
:hourglass: Testing commit d392fba with merge d392fba...

**Comment by japaric** [comment]
@homunkulus r+

**Comment by homunkulus** [comment]
:pushpin: Commit c35bc19 has been approved by `japaric`

**Comment by homunkulus** [comment]
:hourglass: Testing commit c35bc19 with merge c35bc19...

**Comment by homunkulus** [comment]
:sunny: Test successful - [status-travis](https://travis-ci.org/japaric/f3/builds/165991908)
Approved by: japaric
Pushing c35bc197e14d8f7f25e685114138b804718a6c35 to master...

**Pull request merged**
