### PR TITLE
high level API for the gyroscope

### PR DESCRIPTION
**Pull request by japaric**

### CODE REVIEW

**Comment by japaric** [comment]
@homunkulus r+

**Comment by homunkulus** [comment]
:pushpin: Commit 02b2c91 has been approved by `japaric`

**Comment by homunkulus** [comment]
:hourglass: Testing commit 02b2c91 with merge 02b2c91...

**Comment by homunkulus** [comment]
:sunny: Test successful - [status-travis](https://travis-ci.org/japaric/f3/builds/166608653)
Approved by: japaric
Pushing 02b2c91acfb5bb2520a8bda7259fffe80a5ef1f5 to master...

**Pull request merged**
