### PR TITLE
update docs

### PR DESCRIPTION
**Pull request by japaric**

### CODE REVIEW

**Comment by japaric** [comment]
@homunkulus r+

**Comment by homunkulus** [comment]
:pushpin: Commit b9c05fe has been approved by `japaric`

**Comment by homunkulus** [comment]
:hourglass: Testing commit b9c05fe with merge b9c05fe...

**Comment by homunkulus** [comment]
:sunny: Test successful - [status-travis](https://travis-ci.org/japaric/f3/builds/175575405)
Approved by: japaric
Pushing b9c05fe30096e261229caacec5878d27433f19ad to master...

**Pull request merged**
