### PR TITLE
overridable interrupts and use interrupt+wfi in the delay module

### LINKED ISSUE #8: use interrupt+wfi in `delay::ms`

### PR DESCRIPTION
**Pull request by japaric**
closes #8

### CODE REVIEW

**Comment by japaric** [comment]
@homunkulus r+

**Comment by homunkulus** [comment]
:pushpin: Commit 1096367 has been approved by `japaric`

**Comment by homunkulus** [comment]
:hourglass: Testing commit 1096367 with merge 1096367...

**Comment by japaric** [comment]
@homunkulus r+

**Comment by homunkulus** [comment]
:pushpin: Commit d0ea8b0 has been approved by `japaric`

**Comment by homunkulus** [comment]
:hourglass: Testing commit d0ea8b0 with merge d0ea8b0...

**Comment by homunkulus** [comment]
:sunny: Test successful - [status-travis](https://travis-ci.org/japaric/f3/builds/166049135)
Approved by: japaric
Pushing d0ea8b07746685253c3957a118a1935422b51766 to master...

**Pull request merged**
