### PR TITLE
more docs

### PR DESCRIPTION
**Pull request by japaric**

### CODE REVIEW

**Comment by japaric** [comment]
@homunkulus r+

**Comment by homunkulus** [comment]
:pushpin: Commit 2f29a9e has been approved by `japaric`

**Comment by homunkulus** [comment]
:hourglass: Testing commit 2f29a9e with merge 2f29a9e...

**Comment by homunkulus** [comment]
:sunny: Test successful - [status-travis](https://travis-ci.org/japaric/f3/builds/171004257)
Approved by: japaric
Pushing 2f29a9e3b9a5b25a7058fba856528ba4dde87a0a to master...

**Pull request merged**
