### PR TITLE
low level access to I2C

### PR DESCRIPTION
**Pull request by japaric**

### CODE REVIEW

**Comment by japaric** [comment]
@homunkulus r+

**Comment by homunkulus** [comment]
:pushpin: Commit e4d4983 has been approved by `japaric`

**Comment by homunkulus** [comment]
:hourglass: Testing commit e4d4983 with merge e4d4983...

**Comment by homunkulus** [comment]
:broken_heart: Test failed - [status-travis](https://travis-ci.org/japaric/f3/builds/166293332)

**Comment by japaric** [comment]
@homunkulus r+

**Comment by homunkulus** [comment]
:pushpin: Commit ce33c98 has been approved by `japaric`

**Comment by homunkulus** [comment]
:hourglass: Testing commit ce33c98 with merge ce33c98...

**Comment by homunkulus** [comment]
:sunny: Test successful - [status-travis](https://travis-ci.org/japaric/f3/builds/166297024)
Approved by: japaric
Pushing ce33c9804d0a0278e9fe8c10a1c01f3e9c3e02a9 to master...

**Pull request merged**
