### PR TITLE
export_name -> no_mangle

### PR DESCRIPTION
**Pull request by japaric**
fix the override-panic-fmt example to use the lang item rather than the
more unstable symbol

### CODE REVIEW

**Comment by japaric** [comment]
@homunkulus r+

**Comment by homunkulus** [comment]
:pushpin: Commit 504c097 has been approved by `japaric`

**Comment by homunkulus** [comment]
:hourglass: Testing commit 504c097 with merge 504c097...

**Comment by homunkulus** [comment]
:sunny: Test successful - [status-travis](https://travis-ci.org/japaric/f3/builds/176597751)
Approved by: japaric
Pushing 504c097142ee85c4d11d556296c658ca7a7ba9d6 to master...

**Pull request merged**
