### PR TITLE
add an opt-out "examples" Cargo feature to hide the examples module

### PR DESCRIPTION
**Pull request by japaric**

### CODE REVIEW

**Comment by japaric** [comment]
@homunkulus r+

**Comment by homunkulus** [comment]
:pushpin: Commit 0c0385b has been approved by `japaric`

**Comment by homunkulus** [comment]
:hourglass: Testing commit 0c0385b with merge 0c0385b...

**Comment by homunkulus** [comment]
:sunny: Test successful - [status-travis](https://travis-ci.org/japaric/f3/builds/169123941)
Approved by: japaric
Pushing 0c0385b334d683ede67c5c909d6a8cd9a044eabf to master...

**Pull request merged**
