### PR TITLE
tweak the linker script

### PR DESCRIPTION
**Pull request by japaric**

### CODE REVIEW

**Comment by japaric** [comment]
@homunkulus r+

**Comment by homunkulus** [comment]
:pushpin: Commit f813a0b has been approved by `japaric`

**Comment by homunkulus** [comment]
:hourglass: Testing commit f813a0b with merge f813a0b...

**Comment by homunkulus** [comment]
:sunny: Test successful - [status-travis](https://travis-ci.org/japaric/f3/builds/169333820)
Approved by: japaric
Pushing f813a0b05b517624853ab87c7f27b77c6d1193d3 to master...

**Pull request merged**
