### PR TITLE
add Cargo features to opt out of interrupts and static RAM variables

### PR DESCRIPTION
**Pull request by japaric**
"Pay for what you use"

### CODE REVIEW

**Comment by japaric** [comment]
@homunkulus r+

**Comment by homunkulus** [comment]
:pushpin: Commit ac8dc78 has been approved by `japaric`

**Comment by homunkulus** [comment]
:hourglass: Testing commit ac8dc78 with merge ac8dc78...

**Comment by homunkulus** [comment]
:broken_heart: Test failed - [status-travis](https://travis-ci.org/japaric/f3/builds/171723182)

**Comment by japaric** [comment]
@homunkulus r+

**Comment by homunkulus** [comment]
:pushpin: Commit 209ca75 has been approved by `japaric`

**Comment by homunkulus** [comment]
:hourglass: Testing commit 209ca75 with merge 209ca75...

**Comment by homunkulus** [comment]
:sunny: Test successful - [status-travis](https://travis-ci.org/japaric/f3/builds/171724056)
Approved by: japaric
Pushing 209ca752f70330af1a6ec752d27f59b184f4a867 to master...

**Pull request merged**
