### PR TITLE
use the `ref_slice` crate

### PR DESCRIPTION
**Pull request by japaric**
Waiting for a new release

### CODE REVIEW

**Comment by japaric** [comment]
@homunkulus r+

**Comment by homunkulus** [comment]
:pushpin: Commit dd094b1 has been approved by `japaric`

**Comment by homunkulus** [comment]
:hourglass: Testing commit dd094b1 with merge dd094b1...

**Comment by homunkulus** [comment]
:sunny: Test successful - [status-travis](https://travis-ci.org/japaric/f3/builds/172943111)
Approved by: japaric
Pushing dd094b15f5d2438ae21f5ff8a4606b251efa32f5 to master...

**Pull request merged**
