### PR TITLE
initialize the FPU

### PR DESCRIPTION
**Pull request by japaric**

### CODE REVIEW

**Comment by japaric** [comment]
@homunkulus r+

**Comment by homunkulus** [comment]
:pushpin: Commit 35afbd4 has been approved by `japaric`

**Comment by homunkulus** [comment]
:hourglass: Testing commit 35afbd4 with merge 35afbd4...

**Comment by homunkulus** [comment]
:broken_heart: Test failed - [status-travis](https://travis-ci.org/japaric/f3/builds/165430876)

**Comment by japaric** [comment]
@homunkulus r+

**Comment by homunkulus** [comment]
:pushpin: Commit cb0c877 has been approved by `japaric`

**Comment by homunkulus** [comment]
:hourglass: Testing commit cb0c877 with merge cb0c877...

**Comment by homunkulus** [comment]
:sunny: Test successful - [status-travis](https://travis-ci.org/japaric/f3/builds/165685303)
Approved by: japaric
Pushing cb0c8771a74d365b56c32ca8aed2c584902073ea to master...

**Pull request merged**
